---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.application.hostname | replace "." "-" }}
  namespace: {{ .Release.Namespace }}
data:
  application.conf: |
    server {
      listen 80 default_server;
      server_name _;

      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";

      root  /usr/share/nginx/html;
      index index.html

      charset utf-8;

      location / {
        if ($request_uri ~ ^/(.*)\.html) {
          return 302 /$1;
        }
        try_files $uri $uri.html $uri/ =404;
      }

      error_log  /dev/stderr;
      access_log /dev/stdout;
    }
