---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.application.hostname | replace "." "-" }}
  namespace: {{ .Release.Namespace }}
data:
  application.conf: |
    server {
      listen 80 default_server;
      server_name _;

      add_header X-Frame-Options "SAMEORIGIN";
      add_header X-Content-Type-Options "nosniff";
      add_header Content-Security-Policy "default-src 'none'; font-src https://joshgrancell.cdn.grancellconsulting.net; img-src 'self' https://joshgrancell.cdn.grancellconsulting.net https://img.shields.io; object-src 'none'; script-src 'none'; style-src 'self' https://joshgrancell.cdn.grancellconsulting.net;";

      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";

      root  /usr/share/nginx/html;
      index index.html

      charset utf-8;

      location / {
        if ($request_uri ~ ^/(.*)\.html) {
          return 302 /$1;
        }
        try_files $uri $uri.html $uri/ =404;
      }

      error_log  /dev/stderr;
      access_log /dev/stdout;
    }
